name: dolphin_cli
description: The official dev tools Command Line Interface for the Dolphin Framework for Flutter.
version: 0.1.2
homepage: https://github.com/rkishan516/dolphin_cli
repository: https://github.com/rkishan516/dolphin_cli
topics: [cli, codegen, template, boilerplate]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  freezed_annotation: ^2.1.0
  mockito: ^5.4.1
  mustache_template: ^2.0.0
  path: ^1.8.1
  pubspec_yaml: ^3.1.0
  recase: ^4.0.0
  json_annotation: ^4.8.1
  xdg_directories: ^1.0.0
  pub_updater: ^0.4.0
  mason_logger: ^0.2.10
  cli_completion: ^0.4.0
  scoped_zone: ^0.1.0+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.7

  build_runner: ^2.4.4
  freezed: ^2.3.4
  json_serializable: ^6.7.0

executables:
  dolphin:
