name: dolphin_cli
description: The official command-line interface for the Dolphin framework, tailored for Flutter developers.
version: 1.5.0
homepage: https://dolphin.goflutter.in/
repository: https://github.com/rkishan516/dolphin_cli
topics: [cli, codegen, template, boilerplate]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.7.0
  freezed_annotation: ^3.0.0
  mockito: ^5.4.4
  mustache_template: ^2.0.0
  path: ^1.9.1
  pubspec_yaml: ^3.1.0
  recase: ^4.0.0
  json_annotation: ^4.9.0
  xdg_directories: ^1.1.0
  pub_updater: ^0.5.0
  mason_logger: ^0.3.3
  cli_completion: ^0.5.1
  scoped_zone: ^0.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15
  build_runner: ^2.4.15
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  mocktail: ^1.0.4

executables:
  dolphin: dolphin